# Mutat칩k 칠s t치bl치zatok {#sec-mutatok-tablazatok}

```{r}
#| results: "asis"
#| echo: false
source("_common.R")
```


## Az *Alap R* lehet콈s칠gei 游뗵 {#sec-alap-r-lehetosegei}


::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
1. K칠sz칤tsen gyakoris치gi t치bl치zatot a `survey` adatt치bla `Smoke` v치ltoz칩j치ra!
:::

::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
2. K칠sz칤tsen gyakoris치gi t치bl치zatot a `survey` adatt치bla `Smoke` 칠s `Sex` v치ltoz칩j치ra!
:::

::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
3. Hat치rozza meg a pulzus 치tlag치t a `survey` adatt치bla `Sex` 칠s `Smoke` v치ltoz칩i szerint!
:::

## A *Tidyverse R* lehet콈s칠gei 游뱂 {#sec-tidyverse-r-lehetosegei}


::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
1. K칠sz칤tsen gyakoris치gi t치bl치zatot a `survey` adatt치bla `Smoke` v치ltoz칩j치ra! Haszn치lja a *Tidyverse R* csomagjait!
:::

::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
2. K칠sz칤tsen gyakoris치gi t치bl치zatot a `survey` adatt치bla `Smoke` 칠s `Sex` v치ltoz칩j치ra! Haszn치lja a *Tidyverse R* csomagjait!
:::

::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
3. Hat치rozza meg a pulzus 치tlag치t a `survey` adatt치bla `Sex` 칠s `Smoke` v치ltoz칩i szerint! Haszn치lja a *Tidyverse R* csomagjait!
:::

## Halad칩 lehet콈s칠gek 游뱚 {#sec-halado-lehetosegek}


::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
1. K칠sz칤tsen gyakoris치gi t치bl치zatot a `survey` adatt치bla `Smoke` v치ltoz칩j치ra! Haszn치lja a `{DescTools}`, majd a `{summarytools}` csomagot!
:::

::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
2. K칠sz칤tsen gyakoris치gi t치bl치zatot a `survey` adatt치bla `Smoke` 칠s `Sex` v치ltoz칩j치ra! Haszn치lja a `{DescTools}`, majd a `{summarytools}` csomagot!
:::

::: {.callout-warning icon="false"}
## `r emoji("dart")` Feladat
3. Hat치rozza meg a pulzus 치tlag치t a `survey` adatt치bla `Sex` 칠s `Smoke` v치ltoz칩i szerint! Haszn치lja a `{psych}`, `{DescTools}`, majd a `{summarytools}` csomagot!
:::